# railway.toml

[[services]]
name = "ui"
rootDir = "ui"
buildCommand = "npm install && npm run build"
startCommand = "node server.js"

[[services]]
name = "server"
rootDir = "server"
buildCommand = "bundle install"
startCommand = "bundle exec rails server -b 0.0.0.0 -p $PORT"